clc; clear; close all;
load('lena512.mat');    
load('square.mat');      
load('cameraman.mat');   
figure;
subplot(1,3,1);
imagesc(lena512);
colormap(gray);
axis image off;
title('Lena');
subplot(1,3,2);
imagesc(A);
colormap(gray);
axis image off;
title('Square');
subplot(1,3,3);
imagesc(camera512);
colormap(gray);
axis image off;
title('Cameraman');